### ISSUE TITLE
container fails on restart

### ISSUE THREAD

**Issue by TimoKramer** [bob-cd/logger-local#1]
Hi,
https://github.com/bob-cd/logger-local/blob/main/main.go#L218 makes the container fail on restart when the volume is reused because the folder already exists. What is the idea behind this check? Is it ok to reuse the log-folder?

**Comment by TimoKramer** [comment]
do you think this should be fixed? @lispyclouds

**Comment by lispyclouds** [comment]
Just seeing this, I've pushed a fix about 6days ago, might address this in the latest image

**Comment by TimoKramer** [comment]
strange, still seeing 
```
~ $ podman logs muck_logger-local_1 
2025/11/13 13:29:50 ERROR Error starting err="mkdir logs: file exists"
2025/11/13 13:32:50 ERROR Error starting err="mkdir logs: file exists"
```

**Comment by TimoKramer** [comment]
ok, odd... i did pull the image and it still failed but now after deleting the volume it seems to work now

**Comment by lispyclouds** [comment]
Interesting, is it reproducible in any way?

**Comment by TimoKramer** [comment]
no, it was probably my bad... somehow `podman-compose up --pull` does not seem to work as I expected.
